apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "{{ .Values.message }} - This pod is labled with {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }} and is running on {{ .Values.service.nodePort }}.";
       }
   }
}
'
