apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drank: {{ quote .Values.favorite.drink | upper | quote }}
  version: {{ .Chart.Name }}-{{ .Chart.Version }}
